# Uncomment the next line to define a global platform for your project
# platform :ios, '7.0'

target 'Chair' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Chair

  pod 'Realm', '~> 2.1'
  pod 'SDWebImage', '~>3.8'

end
