# Uncomment the next line to define a global platform for your project
# platform :ios, '7.0'

target 'Chair' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Chair

  pod 'Realm', '~> 2.1'
  pod 'SDWebImage', '~>3.8'
  pod 'LGSideMenuController'
  
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crash'
  
  pod 'GoogleSignIn'

end
